CREATE TABLE [dbo].[AuthorRole]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Role] NVARCHAR(50) NOT NULL, 
    [Created] DATETIME2 NULL DEFAULT GetUTCDate(), 
    [Updated] DATETIME2 NULL DEFAULT GETUTCDATE(), 
    [IsActive] BIT NULL DEFAULT 1
)
